name: trade_diary
description: "감자랑 함께 일기를 써봐요 :)"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  pro_image_editor: ^5.1.0
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.12
  json_annotation: ^4.9.0
  markdown_editor_plus: ^0.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/images/
    - .env
  fonts:
    - family: EF_Diary
      fonts:
        - asset: assets/fonts/EF_Diary/EF_Diary.ttf

    - family: PretendardJP
      fonts:
        - asset: assets/fonts/PretendardJP/PretendardJP-Thin.otf
          weight: 100
        - asset: assets/fonts/PretendardJP/PretendardJP-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/PretendardJP/PretendardJP-Light.otf
          weight: 300
        - asset: assets/fonts/PretendardJP/PretendardJP-Regular.otf
          weight: 400
        - asset: assets/fonts/PretendardJP/PretendardJP-Medium.otf
          weight: 500
        - asset: assets/fonts/PretendardJP/PretendardJP-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PretendardJP/PretendardJP-Bold.otf
          weight: 700
        - asset: assets/fonts/PretendardJP/PretendardJP-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/PretendardJP/PretendardJP-Black.otf
          weight: 900

  uses-material-design: true
