name: trade_diary
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  flutter_web_frame: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: EF_Diary
      fonts:
        - asset: assets/fonts/EF_Diary/EF_Diary.ttf

    - family: PretendardJP
      fonts:
        - asset: assets/fonts/PretendardJP/PretendardJP-Thin.otf
          weight: 100
        - asset: assets/fonts/PretendardJP/PretendardJP-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/PretendardJP/PretendardJP-Light.otf
          weight: 300
        - asset: assets/fonts/PretendardJP/PretendardJP-Regular.otf
          weight: 400
        - asset: assets/fonts/PretendardJP/PretendardJP-Medium.otf
          weight: 500
        - asset: assets/fonts/PretendardJP/PretendardJP-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PretendardJP/PretendardJP-Bold.otf
          weight: 700
        - asset: assets/fonts/PretendardJP/PretendardJP-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/PretendardJP/PretendardJP-Black.otf
          weight: 900

  uses-material-design: true
