name: trade_diary
description: "감자랑 함께 일기를 써봐요 :)"

publish_to: "none"

version: 1.0.12+2

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.2"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^18.0.1
  flutter_svg: ^2.3.0
  google_sign_in: ^7.2.0
  supabase_flutter: ^2.17.2
  flutter_dotenv: ^6.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  flutter_quill: ^11.5.1
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.3
  flutter_riverpod: ^3.4.3
  sign_in_with_apple: ^8.2.0
  flutter_screenutil: ^5.9.3
  intl: ^0.20.3
  url_launcher: ^6.3.2
  sentry_flutter: ^9.29.0
  http_parser: ^4.1.2
  flutter_local_notifications: ^22.3.0
  shared_preferences: ^2.5.5
  timezone: ^0.11.1
  flutter_image_compress: ^2.5.1
  home_widget: ^0.9.4
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  json_serializable: ^6.14.1
  freezed: ^4.0.1
  build_runner: ^2.16.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/character/img-potato-7lv.png
  android: true
  ios: true

  android_12:
    image: assets/images/character/img-potato-7lv.png
    icon_background_color: "#ffffff"

flutter:
  assets:
    - assets/images/icons/
    - assets/images/character/
    - .env
  fonts:
    - family: EF_Diary
      fonts:
        - asset: assets/fonts/EF_Diary/EF_Diary.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600

  uses-material-design: true
