// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXtRqtm0SyAelhPxY8omnMOihnA53WiE',
    appId: '1:548875410267:android:2c0b3238030419d1d4987e',
    messagingSenderId: '548875410267',
    projectId: 'potato-4-cut',
    storageBucket: 'potato-4-cut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHcAGyg4VVVPGyscReww1Sp4aqbTbw0c',
    appId: '1:548875410267:ios:07275e1bae3038f3d4987e',
    messagingSenderId: '548875410267',
    projectId: 'potato-4-cut',
    storageBucket: 'potato-4-cut.firebasestorage.app',
    androidClientId: '548875410267-drr7qodgo20lh69fmtf5r3ljeprctd7s.apps.googleusercontent.com',
    iosClientId: '548875410267-0h3h6d3jhhv41crebe48288q813mogdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeDiary',
  );
}
