default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    pubspec = YAML.load_file("../../pubspec.yaml")
    version = pubspec["version"].split('+')
    version_number = version[0]
    build_number = version[1]
     
    increment_version_number(
	version_number: version_number,
	xcodeproj: "Runner.xcodeproj"
    )
    increment_build_number(
	build_number: build_number,
	xcodeproj: "Runner.xcodeproj"
    )

    match(type: "appstore")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", configuration: "Release")
    pilot(
	api_key_path: "fastlane/6ZQ7V7U6U5.json",
	skip_waiting_for_build_processing: true
    )
  end
end