name: Remove old artifacts

on:
  schedule:
    - cron: "15 18 * * *"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "3 days"
