name: flutter-ci
on: [ push, pull_request ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
      - run: flutter pub get
      - run: flutter analyze

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
      - run: flutter pub get
      - run: |
          echo "DB_URL=$DB_URL" >> .env
          echo "DB_KEY"=$DB_KEY >> .env
          echo "REDIRECT_URI"=$REDIRECT_URI >> .env
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_KEY: ${{ secrets.DB_KEY }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
